
export default new Map([
["docs/src/content/docs/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=docs%2Fsrc%2Fcontent%2Fdocs%2Findex.mdx&astroContentModuleFlag=true")],
["docs/src/content/docs/skills/commit-standards.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=docs%2Fsrc%2Fcontent%2Fdocs%2Fskills%2Fcommit-standards.mdx&astroContentModuleFlag=true")],
["docs/src/content/docs/skills/destructive-command-guard.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=docs%2Fsrc%2Fcontent%2Fdocs%2Fskills%2Fdestructive-command-guard.mdx&astroContentModuleFlag=true")],
["docs/src/content/docs/skills/git-safety.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=docs%2Fsrc%2Fcontent%2Fdocs%2Fskills%2Fgit-safety.mdx&astroContentModuleFlag=true")],
["docs/src/content/docs/skills/holocron-skill-client.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=docs%2Fsrc%2Fcontent%2Fdocs%2Fskills%2Fholocron-skill-client.mdx&astroContentModuleFlag=true")],
["docs/src/content/docs/skills/holocron-skill-config.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=docs%2Fsrc%2Fcontent%2Fdocs%2Fskills%2Fholocron-skill-config.mdx&astroContentModuleFlag=true")],
["docs/src/content/docs/skills/holocron-skill-plugin.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=docs%2Fsrc%2Fcontent%2Fdocs%2Fskills%2Fholocron-skill-plugin.mdx&astroContentModuleFlag=true")],
["docs/src/content/docs/skills/holocron-skill-skill.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=docs%2Fsrc%2Fcontent%2Fdocs%2Fskills%2Fholocron-skill-skill.mdx&astroContentModuleFlag=true")],
["docs/src/content/docs/skills/holocron-skill-util.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=docs%2Fsrc%2Fcontent%2Fdocs%2Fskills%2Fholocron-skill-util.mdx&astroContentModuleFlag=true")],
["docs/src/content/docs/skills/pr-workflow.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=docs%2Fsrc%2Fcontent%2Fdocs%2Fskills%2Fpr-workflow.mdx&astroContentModuleFlag=true")],
["docs/src/content/docs/skills/security-review.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=docs%2Fsrc%2Fcontent%2Fdocs%2Fskills%2Fsecurity-review.mdx&astroContentModuleFlag=true")]]);
		